### ISSUE TITLE
Tracking Algo

### ISSUE THREAD

**Issue by a-blue-pig** [a-blue-pig/Robotics_2020#4]
# Tracking Algorithm
## Odometry Branch
The tracking Algorithm didnt work on the *first* try.
Currently working on diagnosing and whatnot.

Bug Status:
- [ ] Check that each step works as intended
- [x] Check the encoders and variables
- [x] Add a serial output to show sensor and variable data
  * this is part of the [telemetry card] (https://app.gitkraken.com/glo/board/XRzStZpIGQAQwoqT/card/XRzUozmGsgAPGAdT)

**Comment by a-blue-pig** [comment]
# Fix 1
Found an error with a variable.
* delta_L_R
* delta_R_R

Fixed and almost done going through diagnosis.

**Comment by a-blue-pig** [comment]
# New Error/Source
While going through all the calculations and variables I found:
* Angle works as intended *(in radians)*
* Everything works until the polar conversion.
The problem is that it returns NAN (Not a Number) which is reserved for imaginary or complex numbers.
After some research: the problem is there is a square root of a negative number or a 0/0.

**Comment by a-blue-pig** [comment]
# found source of problem
Finally found one source of the problem:
* The polar conversions for polar_theta did a 0/0 when stationary
Added a if/else to check for stationary movement and skip the equation to avoid the 0/0.
